**Importing Libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Reading the data**

In [3]:
df = pd.read_csv("/content/digit_svm.csv")

In [4]:
df

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0          1       0       0       0  ...         0         0         0         0
1          0       0       0       0  ...         0         0         0         0
2          1       0       0       0  ...         0         0         0         0
3          4       0       0       0  ...         0         0         0         0
4          0       0       0       0  ...         0         0         0         0
...      ...     ...     ...     ...  ...       ...       ...       ...       ...
41995      0       0       0       0  ...         0         0         0         0
41996      1       0       0       0  ...         0         0         0         0
41997      7       0       0       0  ...         0         0         0         0
41998      6       0       0       0  ...         0         0         0         0
41999      9       0       0       0  ...         0         0         0         0

[42000 rows x 785 columns]

**Dividing input to x and output to y**

In [5]:
x = df.iloc[:, df.columns != 'label'].values

In [6]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
y = df. iloc[:, 0].values

In [8]:
y

array([1, 0, 1, ..., 7, 6, 9])

**Split data for test and train**

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [11]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**Scalling the data**

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()

In [14]:
x_train = sc.fit_transform(x_train)

In [15]:
x_test = sc.fit_transform(x_test)

In [16]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

**Implementing SVM algorithm and training the model**

In [17]:
from sklearn.svm import SVC

In [18]:
clf = SVC(kernel="linear",random_state=0)

In [19]:
clf.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

**Predicting the output**

In [20]:
pred_y = clf.predict(x_test)

In [21]:
pred_y

array([3, 6, 9, ..., 2, 7, 2])

In [22]:
y_test

array([3, 6, 9, ..., 2, 7, 2])

**Checking accuracy of the model**

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
accuracy_score(y_test,pred_y)

0.919404761904762

**Confusion matrix**

In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
confusion_matrix(y_test,pred_y)

array([[778,   0,   7,   4,   3,   6,  11,   0,   3,   1],
       [  0, 947,   4,   1,   0,   1,   1,   2,   5,   0],
       [ 10,   9, 780,  16,  11,   7,   6,   8,  12,   1],
       [  2,   3,  25, 779,   1,  24,   0,   5,  19,   5],
       [  3,   5,   8,   1, 778,   3,   5,   3,   3,  18],
       [  7,   7,   7,  38,   5, 662,   8,   2,  16,   4],
       [  6,   0,  15,   0,  13,  11, 795,   0,   1,   0],
       [  4,   5,  11,   7,  12,   0,   1, 831,   6,  22],
       [  5,  14,  11,  29,   5,  24,   6,   1, 666,   7],
       [ 11,   4,   6,   8,  33,   8,   0,  28,   7, 707]])

**Example: Pixel data of handwritten 3 is given**

In [27]:
df = pd.read_csv("/content/samplefile.csv")

In [28]:
x_test2 = df.iloc[[True]]

In [29]:
x_test2

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0       0       0       0       0  ...         0         0         0         0

[1 rows x 784 columns]

In [32]:
pred_y2 = clf.predict(x_test2)

In [33]:
pred_y2

array([3])